### ISSUE TITLE
Problem in bonetexture serializer

### ISSUE THREAD

**Issue by bianchijonas1** [Kitware/BoneTextureExtension#21] opened 2019-02-07 20:09 UTC
Hello. 

1) When I`m using the Bonetexture Serializer, if I check the box: [] export as csv , the software does not run the analysis. If the box is unchecked It runs normally.

2) the name of the variables are not shown in the CSV file generated by step 1.

3) When I`m using the Bonetexture (for a single case) is not possible to select more than one variable result (to do a CTRL C , CTRL V). I need to do one by one or use the "save table" option.

4) In Bonetexture (single file) the option: "save table" demands a pre-created and named .csv file on my computer. Will be great to have the option to create and named the CSV file in the same screen on 3D slicer and them "save table".

Thank you
Jonas

**Comment by bpaniagua** [comment] 2019-02-07 20:10
Thanks @bianchijonas1 
@phcerdan can you please look into this?

**Comment by phcerdan** [comment] 2019-02-07 20:33
Thanks @bianchijonas1, I will have a look!

**Comment by bianchijonas1** [comment] 2019-02-07 21:02
@phcerdan @bpaniagua thank you, 
If do you need additional information I`ll be glad to collaborate. 
Jonas

**Comment by allemangD** [comment] 2021-07-20 19:46
> In Bonetexture (single file) the option: "save table" demands a pre-created and named .csv file on my computer. Will be great to have the option to create and named the CSV file in the same screen on 3D slicer and them "save table".

@bianchijonas1 Could you clarify what you mean here? These are the steps I've taken to try to reproduce:

- Click the `...` button next to the path selection.
- Navigate to an output folder using the file navigator built into Slicer.
- In the file navigator, type a file name (ex. `output.csv`)
- Click "Save"
- Click "Save Table"

The file is created, even if the file does not yet exist. I think I may be misunderstanding what the issue is.

In the meantime, since I've been able to resolve the other three issues, I'm going to merge those changes and close this issue. If I did misunderstand point 4, or if the workflow I described doesn't work, please reopen this issue or create a new one. 

Thanks!

**Closed** 2021-07-21 08:24 UTC
